
export const RightSectionStyles = {
    Main: {
        width: "78.6%",
        paddingLeft: "90px",
        paddingBottom: "104px",
        paddingTop: "69px",
    },
    Header: {
        fontFamily: 'Gilroy-SemiBold',
        fontWeight: 600,
        fontSize: "20px",
        lineHeight: "24px",
        color: "#000000",
        marginBottom: "25px",
    },
    ProfileImage: {
        marginBottom: "60px",
    },
    Image: {
        width: "120px",
        height: "120px",
        borderRadius: "50%",
    },
    EditIcon: {
        width: "40px",
        height: "40px",
        position: "relative",
        bottom: "2px",
        right: "43px",
        cursor: "pointer",
    },
    Edit: {
        width: "682px",
        display: "flex",
        flexWrap: "wrap",
        gap: "38px 60px",
        marginBottom: "60px",
    },
    Input: {
        display: "flex",
        flexDirection: "column"
    },
    lable: {
        fontFamily: 'Gilroy-Medium',
        fontSize: "18px",
        lineHeight: "27px",
        color: "#000000",
        marginBottom: "7px",
    },
    InputArea: {
        height: "28px",
        width: "269px",
        fontFamily: 'Gilroy-Regular',
        padding: "10px 20px",
        fontSize: "20px",
        lineHeight: "27px",
        borderWidth: "1px",
        borderColor: "#0071C5",
        backgroundColor: "#FFFFFF",
        color: "#000000",
        borderStyle: "solid",
        borderRadius: "6px",
    },
    InputEmail: {
        width: "100%",
    },
    lableEmail: {
        fontFamily: 'Gilroy-Medium',
        fontSize: "18px",
        lineHeight: "27px",
        color: "#CCCCCC",
        marginBottom: "7px",
    },
    InputAreaEmail: {
        height: "28px",
        width: "100%",
        fontFamily: 'Gilroy-Regular',
        padding: "10px 20px",
        fontSize: "20px",
        lineHeight: "27px",
        borderWidth: "1px",
        borderColor: "#CCCCCC",
        backgroundColor: "#FFFFFF",
        color: "#CCCCCC",
        borderStyle: "solid",
        borderRadius: "6px",
        marginTop: "7px",
        cursor: "no-drop",
    },
    btn: {
        display: "flex",
        gap: "0px 25px",
    },
    SaveBtn: {
        width: "51px",
        height: "26px",
        borderRadius: 6,
        fontFamily: "Gilroy-SemiBold",
        color: "#ffffff",
        fontSize: "22px",
        background: "#0071c5",
        padding: "13px 58px 14px 58px",
        textDecoration: "none",
        cursor: "pointer",
    },
    CancelBtn: {
        width: "71px",
        height: "24px",
        border: "1px solid #0071C5",
        borderRadius: 6,
        fontFamily: "Gilroy-SemiBold",
        color: "#0071c5",
        fontSize: "22px",
        background: "#ffffff",
        padding: "13px 47px 14px 47px",
        textDecoration: "none",
        cursor: "pointer",
    }

};
export const LogoutStyles = {
    model: {
        width: "464px",
        height: "246px",
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        background: '#FFFFFF',
        boxShadow: "0px 4px 15px rgba(0, 0, 0, 0.25)",
        borderRadius: "6px",
        outline : 'none'
    },
    ModelHeading: {
        fontFamily: 'Gilroy-Regular',
        fontSize: "23px",
        lineHeight: "27px",
        color: "#000000",
        paddingTop: "31px",
        paddingLeft: "35px",
    },
    Input: {
        fontFamily: 'Gilroy-Regular',
        fontSize: "18px",
        opacity: "0.5",
        lineHeight: "21px",
        color: "#000000",
        paddingTop: "31px",
        paddingLeft: "35px",
    },
    btnGroup: {
        display: "flex",
        justifyContent: "end",
        alignItems: "center",
        gap: "16px",
        marginTop: ' 67px',
        paddingRight: "40px",
    },
    CancelBtn: {
        width: "133px",
        height: "46px",
        borderRadius: 7.7,
        fontFamily: "Gilroy-SemiBold",
        color: "#0071c5",
        fontSize: "22px",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        textDecoration: "none",
        cursor: "pointer",
        border: "1.5px solid #0071c5",
    },
    OkBtn: {
        width: "101px",
        height: "46px",
        borderRadius: 7.7,
        fontFamily: "Gilroy-SemiBold",
        color: "#ffffff",
        fontSize: "22px",
        background: "#0071c5",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        textDecoration: "none",
        cursor: "pointer",

    },
}
