
export const NewProjectStyles = {
    Main: {
        minHeight: "307px",
        backgroundColor: "#F8F9FB",
        display: "flex",
        flexDirection: "column",
        alignItems: "baseline",
        paddingLeft: "102px",
        paddingTop: "81px",
        paddingBottom: "62px",
    },
    Heading: {
        fontSize: "25px",
        fontFamily: "Gilroy-SemiBold",
        fontWeight: 600,
        lineHeight: "30px",
    },
    ButtonsMessage: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexWrap: "wrap",
    },
    Content: {
        marginTop: "22px",
        display: "flex",
        alignItems: "center",
    },
    Button: {
        width: "258px",
        height: "160px",
        backgroundColor: "#ffffff",
        border: "1.3px dashed #0071C5",
        borderRadius: "12px",
        boxShadow: "0px 2px 7px rgba(0, 0, 0, 0.13)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    AddIconImage: {
        width: "57px",
        height: "57px",
        border: "1.5px solid #0071C5",
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    Message: {
        width: "294px",
        height: "70px",
        background: " #FFFFFF",
        borderRadius: "4px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: 'Gilroy-Medium',
        fontSize: "18px",
        lineHeight: "21px",
        marginLeft: "-1px",
        color: "#292929",
    },
    MessageIcon: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    TriangleIcon: {
        width: "19px",
        height: "19px"
    },
    plus: {
        width: "21px",
        height: "21px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "25px",
        color: "#0071C5",
    },
    model: {
        width: "694px",
        height: "343px",
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        background: '#FFFFFF',
        boxShadow: "0px 4px 15px rgba(0, 0, 0, 0.25)",
        borderRadius: "6px",
        outline: 'none'
    },
    ModelHeading: {
        height: "93px",
        width: "100%",
        borderWidth: "1px",
        borderColor: "#CCCCCC",
        borderStyle: "none none solid none",
        fontFamily: 'Gilroy-SemiBold',
        fontSize: "22px",
        lineHeight: "26px",
        color: "#000000",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "346px",
    },
    CrossIcon: {
        width: "24px",
        height: "24px",
    },
    Input: {
        display: "flex",
        flexDirection: "column",
        paddingTop:"31px",
        paddingLeft:"57px",
        marginBottom: "44px",
    },
    lable: {
        fontFamily: 'Gilroy-Medium',
        fontSize: "18px",
        lineHeight: "21px",
        color: "#000000",
        marginBottom: "25px",
    },

    InputArea: {
        height: "30px",
        width: "542px",
        fontFamily: 'Gilroy-Regular',
        padding: "10px 20px",
        fontSize: "20px",
        lineHeight: "27px",
        borderWidth: "1px",
        borderColor: "#0071C5",
        backgroundColor: "#FFFFFF",
        color: "#000000",
        borderStyle: "solid",
        borderRadius: "6px",
    },
    SaveBtn: {
        width: "144px",
        height: "50px",
        borderRadius: 6,
        fontFamily: "Gilroy-SemiBold",
        color: "#ffffff",
        fontSize: "22px",
        background: "#0071c5",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        textDecoration: "none",
        cursor:"pointer",
        marginLeft: "497px",
    },

};

export const SavedProjectsStyles = {
    Main: {
        minHeight: "450px",
        backgroundColor: "#F8F9FB",
        display: "flex",
        paddingBottom: "62px",
        flexDirection: "column",
        alignItems: "baseline",
        paddingLeft: "102px",
        paddingTop: "81px",
    },
    Heading: {
        fontSize: "25px",
        fontFamily: "Gilroy-SemiBold",
        fontWeight: 600,
        lineHeight: "30px",
    },
    Content: {
        marginTop: "22px",
        display: "flex",
        alignItems: "center",
    },
    CardMain: {
        display: "flex",
        gap: "21px 42px",
        flexWrap: "wrap"
    },
    Card: {
        width: "260px",
        height: "162px",
        backgroundColor: "#ffffff",
        borderRadius: "12px",
        boxShadow: "0px 2px 7px rgba(0, 0, 0, 0.13)",
    },
    CardHeadingIcon: {
        display: "flex",
        flexDirection: "row",
    },
    CardHeading: {
        paddingLeft: "31px",
        paddingTop: "33px",
        fontFamily: 'Gilroy-SemiBold',
        fontWeight: "600",
        fontSize: "25px",
        lineHeight: "30px",
        color: "#000000",
    },
    Icon: {},
    Date: {
        paddingLeft: "31px",
        paddingTop: "5px",
        fontFamily: 'Gilroy-Regular',
        fontWeight: "400",
        fontSize: "15px",
        lineHeight: "17px",
        color: "#000000",
    },


};
