package org.openbot.utils;

public class BotFunctionUtils {
  public static String[] botFunctionArray = {
    "moveForward",
    "moveBackward",
    "moveLeft",
    "moveRight",
    "moveOpenBot",
    // "moveCircular",
    "pause",
    "stopRobot",
    "sonarReading",
    "speedReading",
    "voltageDividerReading",
    "frontWheelReading",
    "backWheelReading",
    "gyroscopeReadingX",
    "gyroscopeReadingY",
    "gyroscopeReadingZ",
    "accelerationReadingX",
    "accelerationReadingY",
    "accelerationReadingZ",
    "magneticReadingX",
    "magneticReadingY",
    "magneticReadingZ",
    "indicatorReading",
    "noiseEnable",
    "playSoundSpeed",
    "rightIndicatorOn",
    "leftIndicatorOn",
    "rightIndicatorOff",
    "leftIndicatorOff",
    "ledBrightness",
    "switchDriveMode",
    "switchController",
    "navigationModel",
    "reachGoal",
    "follow",
    "reachPosition",
  };
}
