# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenBot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift', :subspecs => ['Metal']

  # Pods for OpenBot

  target 'OpenBotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenBotUITests' do
    # Pods for testing
  end

end
