# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenBot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']
  pod 'DropDown'
  pod 'Starscream', '~> 3.0.1'
  pod 'GoogleWebRTC'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'GoogleAPIClientForREST/Drive'
  # Pods for OpenBot

  target 'OpenBotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenBotUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
