# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenBot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']
  pod 'DropDown'
  pod 'Starscream', '~> 3.0.1'
  pod 'GoogleWebRTC'

  # Pods for OpenBot

  target 'OpenBotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenBotUITests' do
    # Pods for testing
  end

end
